# Generated by Django 5.0.1 on 2024-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
