# Generated by Django 5.0.1 on 2024-02-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test',
        ),
    ]
